apiVersion: v1
data:
  keyring: CltjbGllbnQuY3Jhc2hdCglrZXkgPSBBUUNHSFA5ZXBIbUZEQkFBVjdNQ0VPdmdiNCs1Umk4cU5pWGxqZz09CgljYXBzIG1vbiA9ICJhbGxvdyBwcm9maWxlIGNyYXNoIgoJY2FwcyBtZ3IgPSAiYWxsb3cgcHJvZmlsZSBjcmFzaCIK
kind: Secret
metadata:
  name: rook-ceph-crash-collector-keyring
  namespace: rook-ceph
type: kubernetes.io/rook
